name: Deploy to EC2

on:
    push:
        branches: [main]
    pull_request_review:
        types: [submitted]

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build Project
              env:
                  CLIENT_PORT: ${{ secrets.CLIENT_PORT }}
                  NEXT_PUBLIC_SERVER_PORT: ${{ secrets.NEXT_PUBLIC_SERVER_PORT }}
              run: |
                  cd web
                  npm ci
                  npm run build
                  cd ..
                  cd server
                  npm ci
                  npx prisma generate --schema=./prisma/schema.prisma
                  npm run build
                  cd ..

            - name: Copy Files to Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}
                  source: "./server, ./web, ./ecosystem.config.cjs"
                  target: "~/rja-tix"

            - name: Run App
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd ~/rja-tix
                      pm2 start ecosystem.config.cjs
